# Generated by Django 3.2 on 2021-04-17 03:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264, verbose_name='Name')),
                ('ContactNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Contact Number')),
                ('Address', models.CharField(max_length=264)),
                ('Age', models.IntegerField()),
                ('Type', models.CharField(choices=[('driver', 'Driver'), ('user', 'User')], default='user', max_length=6)),
                ('RefName1', models.CharField(max_length=264, verbose_name='Emergency Contact Name-1')),
                ('RefContactNo1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-1')),
                ('RefName2', models.CharField(max_length=264, verbose_name='Emergency Contact Name-2')),
                ('RefContactNo2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-2')),
                ('Accuracy', models.IntegerField(default=0)),
                ('no_of_trips', models.IntegerField(default=0)),
                ('no_of_sleeps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
