# Generated by Django 3.2 on 2021-04-17 06:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Emergency Contact Number-1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Emergency Contact Number-2'),
        ),
    ]
