# Generated by Django 3.2 on 2021-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalert', '0002_auto_20210417_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='UserName',
            field=models.CharField(default='GovindShukla213', max_length=264, unique=True, verbose_name='UserName'),
        ),
    ]
