# Generated by Django 3.2 on 2021-05-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalert', '0003_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UserName',
            field=models.CharField(default='GovindShukla213', max_length=264, verbose_name='UserName'),
        ),
    ]
