# Generated by Django 3.2 on 2021-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalert', '0004_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UserName',
            field=models.CharField(max_length=264, unique=True, verbose_name='UserName'),
        ),
    ]
